nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs
npmScopes:
  vsf-enterprise:
    npmRegistryServer: https://registrynpm.storefrontcloud.io
    npmAuthToken: ${NPM_AUTH_TOKEN}
    npmAlwaysAuth: true
