nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs
npmScopes:
  vsf-enterprise:
    npmRegistryServer: https://registrynpm.storefrontcloud.io
    npmAuthToken: CJlT0Xs5F0oaTaV+wRPWAJnQYZhb595in9tR6mG3IdU2j1Nw3Oc3MCvAgbfZ9mjx
    npmAlwaysAuth: true
