name: CI

on:
  push:
    branches: ["develop-ci"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      # Deploy to DigitalOcean using SSH with username and password
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean Droplet via SSH (Username and Password)
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -av --delete ./apps/web/.output/ www-data@${{ secrets.DO_IP }}:/var/www/html/vsf2_tiles247/
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh www-data@${{ secrets.DO_IP }} 'your post-deployment commands here'
        env:
          SSH_USERNAME: www-data
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          DO_IP: ${{ secrets.DO_IP }}
