name: unit-tests

on:
  push:
    branches:
      - develop
      - staging
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
      - staging

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: './.github/.node-version'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
